In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)
data = pd.read_csv("jester-data-1.csv",header = None)
d = data.to_latex()
text_file = open("Output.txt_jokes", "w")
text_file.write(d)
text_file.close()

In [20]:
n_features = 2



train, validation, testing = np.split(data.sample(frac = 1), [int(.8*len(data)), int(.9*len(data))])
del train[0]
user_ratings = train.values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))

ValueError: cannot delete array elements

In [12]:
latent_item_features

array([[ 0.008,  0.301],
       [ 0.201,  0.834],
       [ 0.127,  0.374],
       [ 0.867,  0.982],
       [ 0.458,  0.016],
       [ 0.147,  0.415],
       [ 0.633,  0.162],
       [ 0.732,  0.092],
       [ 0.819,  0.097],
       [ 0.879,  0.616],
       [ 0.521,  0.883],
       [ 0.711,  0.27 ],
       [ 0.54 ,  0.069],
       [ 0.781,  0.914],
       [ 0.515,  0.853],
       [ 0.523,  0.135],
       [ 0.134,  0.204],
       [ 0.991,  0.883],
       [ 0.966,  0.274],
       [ 0.689,  0.433],
       [ 0.591,  0.27 ],
       [ 0.884,  0.303],
       [ 0.539,  0.934],
       [ 0.574,  0.329],
       [ 0.986,  0.589],
       [ 0.975,  0.68 ],
       [ 0.74 ,  0.947],
       [ 0.124,  0.066],
       [ 0.051,  0.433],
       [ 0.081,  0.352],
       [ 0.629,  0.499],
       [ 0.798,  0.798],
       [ 0.044,  0.417],
       [ 0.062,  0.285],
       [ 0.09 ,  0.759],
       [ 0.607,  0.037],
       [ 0.163,  0.147],
       [ 0.723,  0.806],
       [ 0.532,  0.868],
       [ 0.546,  0.691],


In [13]:
latent_user_preferences

array([[ 0.429,  0.425],
       [ 0.713,  0.078],
       [ 0.776,  0.09 ],
       ..., 
       [ 0.1  ,  0.843],
       [ 0.64 ,  0.444],
       [ 0.947,  0.399]])

In [14]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating,alpha = 0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating- rating );
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    


def sgd(iterations = 30):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if(rating!=99):
                    err = train(user_id,item_id,rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if(iteration%1 == 0 ):
            print mse
                    
                    
    


In [15]:
sgd()

26.2983595247
25.2793284492
24.9465773456
24.7017495829
24.467578751
24.2327214136
23.9960877781
23.7587564038
23.5224044124
23.2888667098
23.0599529894
22.837344228
22.6225250235
22.416739758
22.2209684411
22.035919558
21.8620370388
21.699518021
21.5483378932
21.4082792295
21.2789616095
21.1598698444
21.0503786856
20.9497726063
20.8572596622
20.771978748
20.6929997738
20.6193164413
20.5498314601
20.4833343269


In [16]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 1.061,  1.005,  0.971, ...,  1.257,  0.857,  1.462],
       [ 1.612,  1.741,  1.545, ...,  1.57 ,  0.911,  2.046],
       [ 1.458,  1.61 ,  1.409, ...,  1.364,  0.759,  1.822],
       ..., 
       [ 2.846,  2.446,  2.525, ...,  3.763,  2.751,  4.124],
       [ 2.74 ,  2.641,  2.524, ...,  3.172,  2.128,  3.738],
       [ 2.761,  2.822,  2.595, ...,  2.943,  1.853,  3.636]])

In [22]:
values = [zip(user_ratings[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
del data[0]
comparison_data.columns = data.columns
comparison_data.applymap(lambda (x,y): "(%2.3f|%2.3f)"%(x,y))

1                2                3                4    \
0       (99.000|1.061)    (4.850|1.005)   (-0.870|0.971)    (0.240|0.419)   
1        (7.770|1.612)    (8.980|1.741)    (7.430|1.545)   (-8.400|0.859)   
2       (99.000|1.458)   (99.000|1.610)   (99.000|1.409)   (99.000|0.814)   
3        (7.670|4.350)    (7.910|4.024)    (7.620|3.952)    (7.770|1.617)   
4       (-9.420|1.435)   (-1.700|1.371)    (8.930|1.318)   (99.000|0.579)   
5       (99.000|3.441)   (-3.500|3.164)    (0.680|3.120)    (4.370|1.260)   
6       (99.000|0.907)    (1.500|0.616)   (99.000|0.752)   (99.000|0.106)   
7       (3.160|-0.334)  (-4.710|-0.646)  (-4.220|-0.412)  (99.000|-0.474)   
8        (9.370|2.575)    (8.500|2.583)    (9.080|2.405)    (9.080|1.166)   
9        (3.060|1.725)   (-9.950|1.436)   (-2.480|1.516)    (1.070|0.476)   
10      (-2.820|1.038)    (2.670|1.031)   (-0.100|0.966)   (-3.880|0.459)   
11       (7.670|4.123)   (-8.300|4.049)    (0.240|3.822)    (6.650|1.777)   
12      (-2.330|0.489)   (-6.360|0.483)   (-8.740|0.454)   (-0.680|0.214)   
13       (8.110|1.713)    (6.600|1.362)    (1.840|1.485)    (4.470|0.406)   
14       (9.270|0.015)   (-6.460|0.091)    (9.130|0.038)   (-8.500|0.085)   
15       (5.870|1.787)    (1.310|1.893)   (-1.800|1.701)   (99.000|0.913)   
16       (2.140|1.131)   (-0.580|1.051)   (99.000|1.029)   (99.000|0.426)   
17      (99.000|1.977)   (-8.010|1.780)   (99.000|1.781)   (99.000|0.684)   
18      (99.000|3.860)   (99.000|3.653)   (99.000|3.534)   (99.000|1.521)   
19       (2.820|0.905)   (-4.320|0.769)   (-8.640|0.800)   (-8.830|0.265)   
20       (9.080|1.508)    (9.370|1.335)    (9.130|1.351)   (99.000|0.498)   
21       (7.330|3.657)    (7.090|3.566)    (7.430|3.382)    (7.380|1.550)   
22       (8.110|2.465)   (-9.370|2.283)    (7.670|2.240)   (-8.930|0.919)   
23       (0.290|3.042)   (-2.430|3.009)   (-5.870|2.827)   (-0.190|1.334)   
24      (-2.280|2.860)    (4.170|2.540)   (-3.110|2.565)    (5.780|0.954)   
25       (7.910|3.979)    (6.890|3.885)    (7.380|3.681)    (6.890|1.692)   
26     (99.000|-0.493)  (99.000|-0.672)  (99.000|-0.518)  (99.000|-0.408)   
27      (-2.140|0.607)    (0.920|0.346)   (-4.660|0.482)   (-3.110|0.002)   
28       (1.120|2.444)   (-1.120|2.167)   (-3.450|2.190)   (-6.750|0.811)   
29     (-9.610|-2.542)   (9.030|-2.364)  (-9.370|-2.313)  (-9.470|-0.958)   
...                ...              ...              ...              ...   
19956   (-0.290|0.170)   (-9.810|0.140)   (-0.290|0.149)    (1.460|0.045)   
19957  (99.000|-1.524)  (-7.670|-1.470)  (99.000|-1.404)  (99.000|-0.629)   
19958   (-1.750|0.602)   (-2.620|0.564)   (-0.580|0.549)    (3.400|0.232)   
19959    (4.130|0.082)   (-1.210|0.028)   (-0.780|0.059)  (-8.200|-0.019)   
19960   (99.000|0.467)   (-2.570|0.243)    (1.700|0.363)  (99.000|-0.023)   
19961   (-0.390|2.079)    (1.750|2.077)   (-0.490|1.939)   (-0.830|0.933)   
19962   (-0.290|1.731)    (0.680|1.787)   (-0.290|1.632)    (0.100|0.836)   
19963    (5.390|2.053)    (8.740|2.023)    (7.620|1.905)    (5.970|0.893)   
19964   (2.720|-0.203)   (1.600|-0.183)   (2.570|-0.183)  (-6.890|-0.071)   
19965   (99.000|1.425)   (99.000|1.291)   (99.000|1.286)   (99.000|0.502)   
19966   (-6.260|1.241)   (-4.760|1.322)   (-4.850|1.184)   (-5.920|0.642)   
19967   (-1.800|1.059)   (-1.210|1.013)    (1.600|0.973)   (-0.630|0.428)   
19968   (1.210|-0.058)  (-7.820|-0.026)   (4.760|-0.044)   (-3.060|0.007)   
19969    (4.850|1.221)   (-9.810|1.106)    (3.590|1.102)   (-6.700|0.430)   
19970   (99.000|2.784)   (99.000|2.489)   (99.000|2.502)   (99.000|0.945)   
19971    (2.910|1.523)    (2.960|1.168)   (-7.230|1.306)    (2.430|0.316)   
19972   (99.000|2.314)   (99.000|2.389)   (99.000|2.183)   (99.000|1.118)   
19973   (1.890|-0.982)  (-1.750|-0.918)  (-8.540|-0.895)  (-8.350|-0.376)   
19974   (99.000|3.307)   (99.000|3.325)   (99.000|3.091)   (99.000|1.506)   
19975    (2.910|1.685)    (7.140|1.739)    (6.750|1.589)    (5.870|0.813)   
19976    (5.920

In [23]:
comparison_data

1                          2    \
0        (99.0, 1.06096611315)       (4.85, 1.0046522545)   
1        (7.77, 1.61197597148)      (8.98, 1.74142806884)   
2        (99.0, 1.45779724114)      (99.0, 1.61040960868)   
3        (7.67, 4.35048831216)       (7.91, 4.0236532655)   
4       (-9.42, 1.43483492922)      (-1.7, 1.37058964861)   
5         (99.0, 3.4406318621)      (-3.5, 3.16449328274)   
6       (99.0, 0.906606791344)      (1.5, 0.615878252406)   
7      (3.16, -0.334318111101)   (-4.71, -0.646031359674)   
8        (9.37, 2.57547268227)       (8.5, 2.58308963476)   
9        (3.06, 1.72513428238)     (-9.95, 1.43606509706)   
10       (-2.82, 1.0382619571)      (2.67, 1.03109714528)   
11       (7.67, 4.12315718599)      (-8.3, 4.04909478628)   
12     (-2.33, 0.488846716757)    (-6.36, 0.483093236053)   
13       (8.11, 1.71320488752)       (6.6, 1.36183466731)   
14     (9.27, 0.0151116144775)   (-6.46, 0.0907270272422)   
15       (5.87, 1.78717342626)      (1.31, 1.89260381189)   
16       (2.14, 1.13079573354)     (-0.58, 1.05133148314)   
17       (99.0, 1.97738090574)     (-8.01, 1.77960436942)   
18         (99.0, 3.860399124)      (99.0, 3.65307926873)   
19      (2.82, 0.905262340327)      (-4.32, 0.7686043324)   
20       (9.08, 1.50839068354)      (9.37, 1.33487543621)   
21       (7.33, 3.65709277778)      (7.09, 3.56598734319)   
22       (8.11, 2.46455200574)     (-9.37, 2.28278038159)   
23        (0.29, 3.0422143908)     (-2.43, 3.00934046576)   
24      (-2.28, 2.86048205064)      (4.17, 2.54033349311)   
25       (7.91, 3.97929422155)      (6.89, 3.88512794525)   
26      (99.0, -0.49289233518)    (99.0, -0.672101875887)   
27     (-2.14, 0.606702298017)     (0.92, 0.346068353725)   
28       (1.12, 2.44422584479)     (-1.12, 2.16679589792)   
29      (-9.61, -2.5418303989)      (9.03, -2.3635873197)   
...                        ...                        ...   
19956  (-0.29, 0.170016566127)    (-9.81, 0.139548235935)   
19957   (99.0, -1.52446990067)    (-7.67, -1.47025012785)   
19958  (-1.75, 0.601773276721)    (-2.62, 0.564402331135)   
19959  (4.13, 0.0821639471179)   (-1.21, 0.0283955083231)   
19960   (99.0, 0.467169788192)     (-2.57, 0.24313785827)   
19961   (-0.39, 2.07902236579)      (1.75, 2.07709610636)   
19962   (-0.29, 1.73076736725)      (0.68, 1.78662353562)   
19963    (5.39, 2.05305794929)      (8.74, 2.02347832319)   
19964  (2.72, -0.203124935588)     (1.6, -0.183375833868)   
19965    (99.0, 1.42453342464)      (99.0, 1.29087763233)   
19966   (-6.26, 1.24145571558)     (-4.76, 1.32245593915)   
19967     (-1.8, 1.0591158341)     (-1.21, 1.01272389798)   
19968  (1.21, -0.058266597799)  (-7.82, -0.0264929529805)   
19969    (4.85, 1.22092940289)     (-9.81, 1.10593909077)   
19970    (99.0, 2.78408710809)      (99.0, 2.48880606102)   
19971    (2.91, 1.52300369744)      (2.96, 1.16774607588)   
19972    (99.0, 2.31436780354)      (99.0, 2.38876387168)   
19973  (1.89, -0.981848368519)   (-1.75, -0.918471852284)   
19974    (99.0, 3.30725806979)      (99.0, 3.32548438291)   
19975    (2.91, 1.68545406105)      (7.14, 1.73893262666)   
19976    (5.92, 0.85960853822)      (2.57, 1.04832148162)   
19977     (0.1, 1.24923961474)      (-3.5, 1.23994789599)   
19978   (-6.17, 4.16471556674)      (7.18, 3.82824674798)   
19979     (6.5, 3.24154603205)      (6.65, 3.14860137281)   
19980   (-1.84, 2.06535967277)     (-0.58, 1.92663154313)   
19981   (-0.29, 0.25414746054)    (2.28, 0.0100847953429)   
19982    (-8.98, 1.8856708644)      (0.68, 1.57955095495)   
19983    (8.93, 2.84558011578)      (9.13, 2.44613497827)   
19984   (-0.83, 2.73973559689)      (4.71, 2.64088871961)   
19985    (99.0, 2.76126117347)      (99.0, 2.82234807958)   

                            3                          4    \
0       (-0.87, 0.971422479638)     (0.24, 0.418615349592)   
1         (7.43, 1.54528998111)     (-8.4, 0.859308907517)   
2           (99.0, 1.408955092)     (99.0, 0.814029210403)

In [24]:
d = comparison_data.to_latex()
text_file = open("comparison_jokes.txt", "w")
text_file.write(d)
text_file.close()